# Generated by Django 5.1.5 on 2025-01-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateTimeField()),
                ('afbeelding', models.ImageField(upload_to='films/')),
                ('beschrijving', models.TextField()),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
    ]
