# Generated by Django 5.1.5 on 2025-01-21 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_location_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='films.room'),
        ),
    ]
