# Generated by Django 5.1.5 on 2025-01-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_alter_film_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name': 'Film', 'verbose_name_plural': 'Films'},
        ),
        migrations.AlterField(
            model_name='film',
            name='afbeelding',
            field=models.ImageField(blank=True, null=True, upload_to='films/'),
        ),
        migrations.AlterField(
            model_name='film',
            name='beschrijving',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='film',
            name='tickets_available',
            field=models.PositiveIntegerField(),
        ),
    ]
