# Generated by Django 5.1.5 on 2025-01-21 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_alter_film_options_alter_film_afbeelding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='room',
        ),
        migrations.RemoveField(
            model_name='film',
            name='tickets_available',
        ),
    ]
