# Generated by Django 5.1.5 on 2025-01-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_remove_film_room_remove_film_tickets_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateTimeField(),
        ),
    ]
