# Generated by Django 5.1.5 on 2025-01-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_alter_film_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='min_leeftijd',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
    ]
