# Generated by Django 5.1.5 on 2025-01-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_film_min_leeftijd'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='films', to='films.room'),
        ),
    ]
