# Generated by Django 5.1.5 on 2025-01-21 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('films', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aantal_tickets', models.PositiveIntegerField()),
                ('reserveringsdatum', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'In behandeling'), ('confirmed', 'Bevestigd'), ('cancelled', 'Geannuleerd')], default='pending', max_length=20)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserveringen', to='films.film')),
                ('gebruiker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserveringen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
