# Generated by Django 5.1.5 on 2025-01-21 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_alter_film_release_date'),
        ('reserveringen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('reserveringen', models.PositiveIntegerField(default=0)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='films.film')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.location')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.room')),
            ],
        ),
    ]
