# Generated by Django 5.1.5 on 2025-01-21 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserveringen', '0002_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='reserveringen',
            new_name='beschikbare_plekken',
        ),
    ]
