# Generated by Django 5.1.5 on 2025-01-21 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserveringen', '0003_rename_reserveringen_event_beschikbare_plekken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='beschikbare_plekken',
            new_name='totaal_aantal_plekken',
        ),
    ]
