# Generated by Django 5.1.5 on 2025-01-22 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserveringen', '0004_rename_beschikbare_plekken_event_totaal_aantal_plekken'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservering',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reserveringen', to='reserveringen.event'),
        ),
    ]
