# Generated by Django 5.1.5 on 2025-01-22 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_film_min_leeftijd'),
        ('reserveringen', '0005_reservering_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservering',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film'),
        ),
    ]
