# Generated by Django 5.1.5 on 2025-01-22 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserveringen', '0006_alter_reservering_film'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservering',
            name='film',
        ),
    ]
