# Generated by Django 5.1.5 on 2025-01-22 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserveringen', '0007_remove_reservering_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservering',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserveringen', to='reserveringen.event'),
        ),
    ]
