# Generated by Django 5.1.5 on 2025-01-19 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=50)),
                ('reserveringen', models.JSONField(blank=True, default=list)),
                ('opgeslagen', models.JSONField(blank=True, default=list)),
                ('leeftijd', models.PositiveIntegerField(blank=True, null=True)),
                ('aantal_recente_reserveringen', models.PositiveIntegerField(default=0)),
                ('taal', models.CharField(default='Nederlands', max_length=50)),
                ('favoriete_genres', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userdata', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Data',
                'verbose_name_plural': 'User Data',
            },
        ),
    ]
