# Generated by Django 5.1.5 on 2025-01-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='leeftijd',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
