# Generated by Django 5.1.5 on 2025-01-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userdata_profiel_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='profiel_foto',
            field=models.ImageField(default='default_profile.webp', upload_to=''),
        ),
    ]
